### ISSUE TITLE
Make it illegal to allocate RGB8 multisampled renderbuffers in WebGL 2.0

### ISSUE THREAD

**Issue by kenrussell** [KhronosGroup/WebGL#2014] opened 2016-09-07 05:08 UTC
RGB8 multisampled renderbuffers can't be allocated successfully on macOS. It was believed that emulating these on top of RGBA8 renderbuffers would be straightforward, but there are more complexities than at first glance. See #1986 .

Per discussion in the WebGL working group, it is believed that a small change to the specification is warranted in this area, prohibiting the allocation of multisampled RGB8 renderbuffers. A conformance test for this is needed.

**Comment by zhenyao** [comment] 2016-12-03 00:47
Close this issue as the test failure that leads us to this conclusion is caused by a Chrome driver bug workaround (apparently an incorrect one).

**Closed by zhenyao** 2016-12-03 00:47 UTC
