### ISSUE TITLE
srcData type for compressedTex[Sub]Image{2,3}D

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/WebGL#2689] opened 2018-08-06 08:03 UTC
Texture functions for uploading compressed formats do not have any type parameter, yet the spec uses `ArrayBufferView ` for `srcData`. GPU compressed formats are defined as opaque blocks of 8 or 16 bytes so they cannot be represented with any "element" type. The only reasonable typed view seems to be `Uint8Array` (and probably `ArrayBuffer` as discussed in #2667).

**Comment by kenrussell** [comment] 2018-08-08 00:35
True, these basically only accept Uint8Array. They will be updated to also accept ArrayBuffer in #2667. Let me close this as a duplicate of the other issue, which will be addressed.

**Closed by kenrussell** 2018-08-08 00:35 UTC
