### ISSUE TITLE
Shader compiler errors on macros

### ISSUE THREAD

**Issue by pixelnerve** [KhronosGroup/WebGL#1962] opened 2016-08-11 19:40 UTC
The following macros fail to compile on WebGL.

```
#define CBUFFER_BEGIN_BINDING( name, bindingIndex ) layout( std140 ) uniform name##_s {
#define CBUFFER_BEGIN( name ) 						layout( std140 ) uniform name##_s {
#define CBUFFER_END( name ) 						} name;

```

The error messages are:

ERROR: 0:6: '#' : invalid character 
ERROR: 0:6: '_s' : syntax error

**Comment by kenrussell** [comment] 2016-08-12 17:59
The ## operator is not present in GLSL ES 3.00. Per GLSL ES 3.00.4, section 3.4, "Preprocessor", page 12:

"There are no number sign based operators (e.g. no # or #@), no ## operator, nor is there a sizeof
operator."

Closing; this is not a bug.

**Closed by kenrussell** 2016-08-12 17:59 UTC
