### ISSUE TITLE
[webGL2.0] Textureprojoffset failed in AMD graphics for OpenGL rendering

### ISSUE THREAD

**Issue by Elainejly** [KhronosGroup/WebGL#2033] opened 2016-09-19 02:47 UTC
OS: w10
Graphics: AMD asic
browser: firefox/chrome
config: enable webGL2.0, enable OpenGL rendering

steps: 
1) run chrome with "--enable-unsafe-es3-apis --enable-experimental-canvas-features"
1) visit "https://www.khronos.org/registry/webgl/sdk/tests/webgl-conformance-tests.html?version=2.0.0"
2) find test "all/deqp/functional/gles3/shadertexturefunction/textureprojoffset" and run

expected: test pass
actually: failed: texture_function.textureprojoffset.sample2dshadow_vertex: Fail
          there are two pixels less in the first column in the "Result" frame dump compared with "Reference"

Root cause: 
    the number of 23, 24, 25, 26, 28 points in the draw, are trying to sample the texture with coordinate (u=0, v=xxx), which value is not defined for filter GL_REPEAT. you need to add an offset 0.5/256 (256 is texture width) to u if you want to get the exact value.   
    file: WebGL-master\sdk\tests\deqp\functional\gles3\es3fShaderTextureFunctionTests.js line: 2384
     es3fShaderTextureFunctionTests.getCaseSpec('sampler2dshadow', es3fShaderTextureFunctionTests.TexFunction.TEXTUREPROJ, [0.2, 0.6, 0.0, 1.5], [-2.25, -3.45, 1.5, 1.5],    false,    0.0,    0.0,    true, [-8, 7, 0],    tex2DShadow, es3fShaderTextureFunctionTests.evalTexture2DShadowProjOffset, es3fShaderTextureFunctionTests.CaseFlags.VERTEX),
               
Suggestion solution: 
    Change the offset to avoid sampling with u=0. [-8, 7, 0] -> [7,-8,0]

Attach file include the first 36 attributes of webgl_b735f978b01bb186 in the test draw.
[vertex and texture.xlsx](https://github.com/KhronosGroup/WebGL/files/479174/vertex.and.texture.xlsx)

**Comment by kenrussell** [comment] 2016-09-19 21:58
@phaulos could you help us evaluate this bug report? I confirmed that the JavaScript port of these tests is identical to the C++ version in this area, so presumably if the JS test is wrong, the native one should be updated too.

CC'ing @zhenyao @kainino0x @jdashg .

**Comment by phaulos** [comment] 2016-09-19 22:00
Those tests are known to suffer from false negatives caused by precision and rounding differences. We are not actively working on fixing them but rather focus on eventually replacing them with a better designed system.

Many of the tests are excluded from Android CTS for that reason.

**Comment by kenrussell** [comment] 2016-09-19 22:34
Ah. Thanks @phaulos for your feedback.

I looked through the top-of-tree dEQP's files like gles3-hw-issues.txt and can confirm that many of the dEQP-GLES3.functional.shaders.texture_functions tests are disabled.

I'd like to preserve as many of these tests as possible for the WebGL 2.0 conformance suite. Most of them seem to pass on all vendors' hardware and they add good value.

I've confirmed on my Windows workstation with AMD GPU that the change suggested by @Elainejly  makes the test pass on Chrome Canary with --use-angle=gl, without affecting the test's behavior for ANGLE's default D3D11 backend. Submitting a pull request making this change.

**Comment by kenrussell** [comment] 2016-09-19 22:37
#2039 uploaded fixing this issue as suggested. Thanks @Elainejly for the suggested fix.

**Comment by Elainejly** [comment] 2016-09-20 07:56
Really appreciate for your quick fix *_*

I am running through webGL2.0 test with AMD driver, almost all tests pass now.

Besides the two tickets filed yesterday, there are three more tests fail both with AMD asic and NV asic, there are:
Mul_dynamic_lowp
Mul_dynamic_mediump
Mul_dynamic_highp

I only checked test case shader_matrix.mul.dynamic.lowp_mat2_mat2_vertex, and found the result is correctly render, the issue is with reference image, you may have a wrong compute for the reference image.

Attach the first 5 vertexes drawn in shader_matrix.mul.dynamic .lowp_mat2_mat2_vertex, according to my calculate, render result is ok.

Could you like me to create another ticket for this failure?

Thanks,
Elaine

**Comment by kenrussell** [comment] 2016-09-20 21:38
@Elainejly : yes, please file a new issue for the other failing tests. Please be very precise about what is failing and on what platform. Provide links to the top-level HTML file, the full test names of the failing tests, and about:gpu from Chrome when running the tests. Thanks.

**Comment by kenrussell** [comment] 2016-09-20 21:38
This issue is resolved. Closing.

**Closed by kenrussell** 2016-09-20 21:38 UTC
